name: Caller workflow

on:
  push:
    branches:
      - main

jobs:
  call_reusable_workflow:
    name: 'Call reusable workflow'
    uses: ./.github/workflows/reusable-workflow.yml
    secrets:
      envPAT2: ${{ secrets.envPAT }}
