name: Caller workflow

on:
  push:
    branches:
      - main

jobs:
  call_reusable_workflow:
    runs-on: ubuntu-latest
    name: Call reusable workflow
    uses: ./.github/workflows/reusable-workflow.yml@main
